# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
default:
    image: python:3.9.2-buster
    before_script:
        - python --version ; pip --version  # For debugging
        - "echo \"Debug: All Env variables\""
        - env
        - pip install virtualenv
        - python -m venv ./venv
        - source venv/bin/activate
        - curl --output rustup.sh --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs # due to python twine
        - sh rustup.sh -y

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip

stages:
    - build
    - test
    - deploy

build:
    stage: build
    script:
        - pip install -e ".[dev]"

test:
    stage: test
    script:
        - pip install -e ".[dev]"
        - python -m coverage run --source=src/camguard -m unittest -v
        - python -m coverage report -m
        - python -m coverage xml
    artifacts:
        paths:
            - ./coverage.xml

pages:
    stage: deploy
    script:
        - pip install -e ".[dev]"
        - make -C ./docs html
        - mkdir ./public
        - cp -r ./docs/_build/html* ./public
    artifacts:
        paths:
            - ./public 
    rules:
        - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"

report:
    stage: deploy
    script:
        # Install deepsource CLI
        - curl https://deepsource.io/cli | sh
        # Set DEEPSOURCE_DSN env variable from repository settings page
        - export DEEPSOURCE_DSN=https://ff59e9aa168344afa352eda62e1e684c@deepsource.io
        # Set CODECOV env variable
        - export CODECOV_TOKEN='430bff0a-5869-4f49-9b5a-ecd0ec0322e5'
        # Report coverage artifact to 'test-coverage' analyzer
        - ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml
    artifacts:
        reports:
            coverage_report:
                coverage_format: cobertura
                path: ./coverage.xml

deploy:
    stage: deploy
    script: "echo \"Deploy is still a: TODO\""
    rules:
        - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
