# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: 3.9.18-bookworm 

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip

stages:
    - build
    - test
    - deploy

build:
    stage: build
    script:
        - python --version ; pip --version  # For debugging
        - pip install virtualenv
        - python -m venv ./venv
        - source venv/bin/activate
        - pip install -e ".[dev]"

test:
    stage: test
    script:
        - coverage run --source=src/camguard -m unittest -v
        - coverage report -m
        - coverage xml

pages:
    stage: deploy
    script:
        - make -C ./docs
    artifacts:
        paths:
            - build/html/*
    rules:
        - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"

deploy:
    stage: deploy
    script: "echo \"Deploy is still a: TODO\""
    rules:
        - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
