# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
default:
    image: python:3.9.2-alpine3.13 
    before_script:
        - python --version ; pip --version  # For debugging
        - pip install virtualenv
        - python -m venv ./venv
        - source venv/bin/activate
        - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -y # due to python twine

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip

stages:
    - .pre
    - build
    - test
    - deploy

prepare:
    stage: .pre
    script:
        - "echo \"Debug: All Env variables\""
        - env

build:
    stage: build
    script:
        - pip install -e ".[dev]"

test:
    stage: test
    script:
        - python -m coverage run --source=src/camguard -m unittest -v
        - python -m coverage report -m
        - python -m coverage xml

pages:
    stage: deploy
    script:
        - make -C ./docs
    artifacts:
        paths:
            - build/html/*
    rules:
        - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"

deploy:
    stage: deploy
    script: "echo \"Deploy is still a: TODO\""
    rules:
        - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
