# for running tox with travis there is no straight forward solution, see:
# https://docs.travis-ci.com/user/languages/python/#using-tox-as-the-build-script
language: generic

jobs:
  include:
    - name: "install python 3.7.3"
      python: '3.7.3'
      install: make install-dev

script: 
    - make check
