# for running tox with travis there is no straight forward solution, see:
# https://docs.travis-ci.com/user/languages/python/#using-tox-as-the-build-script
# therefore running tests and coverage is done manually for travis
language: python

jobs:
    include:
        - name: "setup python 3.7.3"
          language: python
          python: "3.7.3"
          install: 
            - pip install -U six # six is not up to date in travis image
            - make install-dev

script:
    # run test with coverage
    - coverage run --source=src/camguard -m unittest -v
    # show report on stdout
    - coverage report -m

# Report results to DeepSource
after_success:
  # Generate coverage report in xml format
  - coverage xml

  # Install deepsource CLI
  - curl https://deepsource.io/cli | sh

  # Set DEEPSOURCE_DSN env variable from repository settings page
  - export DEEPSOURCE_DSN=https://ff59e9aa168344afa352eda62e1e684c@deepsource.io

  # Set CODECOV env variable
  - export CODECOV_TOKEN='430bff0a-5869-4f49-9b5a-ecd0ec0322e5'

  # Report coverage artifact to 'test-coverage' analyzer
  - ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml
